### ISSUE TITLE
Visual bugs in Chromium

### ISSUE THREAD

**Issue by boardfish** [SLUGSoc/website#22]

**Comment by boardfish** [comment]
![Cards aren't displaying](https://i.gyazo.com/0d100c752cf16300d5cb84e23bb8db96.png)

![Strange margins on event show](https://i.gyazo.com/19ba8468a99584fe10f5625fef93927d.png)

**Comment by boardfish** [comment]
@SkywardWind determined that the second bug occurs as a result of the link being too long. The fix for #23 might knock that one out.

**Comment by boardfish** [comment]
Closing for now as vertical layout should render this a non-issue, but there's a chance it might resurface.

**Comment by SkywardWind** [comment]
![](https://i.gyazo.com/e312e20db0051ab6147dc85712701a91.png)
 Event banners are distorted in the new layout

**Comment by boardfish** [comment]
Not for me... Chrome's back at it again. I'll look into this again soon, but priority's a pinch lower as at least the text is visible now.

**Comment by boardfish** [comment]
Chrome on mobile doesn't seem to have this issue.

**Comment by boardfish** [comment]
Currently a duplicate.
