### ISSUE TITLE
Links aren't clickable in event descriptions 

### ISSUE THREAD

**Issue by SkywardWind** [SLUGSoc/website#23]
![](https://i.gyazo.com/19ba8468a99584fe10f5625fef93927d.png)

There are sometimes links in our event descriptions. On the website the description is in plain text so links aren't clickable.

**Comment by boardfish** [comment]
I'll probably need some kind of filter for what comes in to convert stuff to links and, hopefully, shorten them if they're long.

**Comment by boardfish** [comment]
[This method](https://coderwall.com/p/0ktfmw/ruby-make-plain-text-links-clickable) resulted in common errors where text followed by a colon would be considered a link. Looking into [this gem](https://rubygems.org/gems/rails_autolink) now.

**Comment by boardfish** [comment]
Seems as though [this](https://coderwall.com/p/0ktfmw/ruby-make-plain-text-links-clickable) might be the ticket!
