### ISSUE TITLE
Reduce number of resource calls:

### ISSUE THREAD

**Issue by Aterfax** [SLUGSoc/website#28]
Waterfall analysis shows a lot of resource calls which can probably be reduced.

https://gtmetrix.com/reports/slugsoc.co.uk/VslGQJL8

![image](https://user-images.githubusercontent.com/8648058/46586167-64bd2500-ca72-11e8-9513-54afbd3c39b9.png)

I believe it is currently showing 33 JS calls which is a bit much.

**Comment by boardfish** [comment]
I guess that's the downside of using a framework... Not really sure there's much that can be done about this one. Also worth noting that half of them are specific to parts of the admin portal (events, games etc.), which currently don't have any content.

**Comment by boardfish** [comment]
It's a caveat of Bootstrap, and I think I'll leave it at that.
