### ISSUE TITLE
Reduce or remove blocking elements for page loads

### ISSUE THREAD

**Issue by Aterfax** [SLUGSoc/website#30]
Some external resources are causing loading blockages. 

These should probably be removed for locally loaded assets.

See waterfall: https://gtmetrix.com/reports/slugsoc.co.uk/VslGQJL8

![image](https://user-images.githubusercontent.com/8648058/46586196-c5e4f880-ca72-11e8-9687-f609ce634aa9.png)

**Comment by boardfish** [comment]
I take it those big beige bars represent the blockages? In that case, what's `2959`... linking to?

I might have to look into FontAwesome – I still need to call off to their servers for their JS, but if I can have it local, that'd be nice.

**Comment by Aterfax** [comment]
If you have a look on the link and click the waterfall drop down it should show the offending requests :)

Beige / brown = blocking.

Should be alleviated by async loading from the same webserver (where possible) as far as I know.

**Comment by boardfish** [comment]
[This tutorial](https://flaviocopes.com/javascript-async-defer/#no-defer-or-async-in-the-head) seems like it'll be useful here.
