### ISSUE TITLE
Inline small JS and minify other JS files

### ISSUE THREAD

**Issue by Aterfax** [SLUGSoc/website#31]
Jquery, popper, bootstrap etc...  JS assets could save a significant % by minifying.

Some of these resource calls probably should also be collapsed into one.

![image](https://user-images.githubusercontent.com/8648058/46586220-296f2600-ca73-11e8-8bd4-6df53df80d87.png)

**Comment by boardfish** [comment]
Apparently this isn't happening because the site isn't running in production mode. Should be a quick fix.

**Comment by boardfish** [comment]
This should've been fixed now, but even so, it's only kilobytes. Assuming it's fixed.
