### ISSUE TITLE
Reduce or remove query string from resources

### ISSUE THREAD

**Issue by Aterfax** [SLUGSoc/website#32]
Some caching software will not cache any files served with a query string. If the number of these assets can be reduced or query strings removed that would remove this issue.

![image](https://user-images.githubusercontent.com/8648058/46586256-c92cb400-ca73-11e8-927f-9233013555ff.png)

**Comment by boardfish** [comment]
I'm noticing that all of these are JS files. For now, I think only Bootstrap makes use of those (as seen in the `bootstrap`/`rails-ujs`/`popper` mentions), as we don't currently stock any page-specific JS, even if there's scope for it (probably in `app/assets/javascripts/`). How major of an issue would you consider this to be?

**Comment by Aterfax** [comment]
Well, in theory getting rid of the theory string would be straightforward (I would have thought an easy fix) - but in terms of needed - it would be optimal (but hardly urgent) for reducing redownloads of all those files on subsequent reloads of the site since some web browsers will not cache it as is.

**Comment by boardfish** [comment]
Withdrawing this issue - I don't think it significantly contributes to user experience.
