### ISSUE TITLE
Banners on event are distorted

### ISSUE THREAD

**Issue by SkywardWind** [SLUGSoc/website#40]
![image](https://user-images.githubusercontent.com/43111465/49430304-8e5ca900-f7a2-11e8-8f8c-2ae5cf6e06e0.png)

The aspect ratio of the event banners is wrong. 

I'm using Chrome.

**Comment by boardfish** [comment]
Found the issue - they're using w-100 tags, which make the width 100%. Unfortunately, that also means they don't retain aspect ratio.
